/** Codes must match WooCommerce's IR state list exactly (wp-content/plugins/woocommerce/i18n/states.php) — the Store API rejects checkout otherwise. */
export const IRAN_PROVINCES = [
  { code: "THR", name: "تهران" },
  { code: "ESF", name: "اصفهان" },
  { code: "RKH", name: "خراسان رضوی" },
  { code: "FRS", name: "فارس" },
  { code: "EAZ", name: "آذربایجان شرقی" },
  { code: "WAZ", name: "آذربایجان غربی" },
  { code: "KHZ", name: "خوزستان" },
  { code: "MZN", name: "مازندران" },
  { code: "GIL", name: "گیلان" },
  { code: "ABZ", name: "البرز" },
  { code: "KRN", name: "کرمان" },
  { code: "GZN", name: "قزوین" },
  { code: "QHM", name: "قم" },
  { code: "MKZ", name: "مرکزی" },
  { code: "HRZ", name: "هرمزگان" },
  { code: "SMN", name: "سمنان" },
  { code: "YZD", name: "یزد" },
  { code: "ZJN", name: "زنجان" },
  { code: "GLS", name: "گلستان" },
  { code: "ADL", name: "اردبیل" },
  { code: "KRH", name: "کرمانشاه" },
  { code: "HDN", name: "همدان" },
  { code: "LRS", name: "لرستان" },
  { code: "KRD", name: "کردستان" },
  { code: "BHR", name: "بوشهر" },
  { code: "CHB", name: "چهارمحال و بختیاری" },
  { code: "SKH", name: "خراسان جنوبی" },
  { code: "NKH", name: "خراسان شمالی" },
  { code: "KBD", name: "کهگیلویه و بویراحمد" },
  { code: "ILM", name: "ایلام" },
  { code: "SBN", name: "سیستان و بلوچستان" },
] as const;
