import type { Post, Product, ProductCategory } from "@/lib/types";

/**
 * Placeholder content used until the WordPress + WooCommerce backend is
 * connected (see src/lib/wordpress and src/lib/woocommerce). Shaped to
 * match what those clients return, so switching data sources later is a
 * drop-in swap — see lib/data.ts.
 */

export const CATEGORIES: ProductCategory[] = [
  // top-level (mirrors the cat-grid on the homepage and the main nav)
  { id: "1", slug: "laptop", name: "لپ‌تاپ", icon: "laptop" },
  { id: "2", slug: "desktop", name: "کامپیوتر", icon: "desktop" },
  { id: "3", slug: "console", name: "کنسول بازی", icon: "gamepad" },
  { id: "4", slug: "monitor", name: "مانیتور", icon: "monitor" },
  { id: "5", slug: "parts", name: "قطعات سخت‌افزار", icon: "cpu" },
  { id: "6", slug: "storage", name: "ذخیره‌سازی", icon: "drive" },
  { id: "7", slug: "accessories", name: "لوازم جانبی گیمینگ", icon: "headset" },
  { id: "8", slug: "network", name: "شبکه و اینترنت", icon: "wifi" },

  // لپ‌تاپ
  { id: "1-1", slug: "laptop-gaming", name: "لپ‌تاپ گیمینگ", icon: "laptop", parentSlug: "laptop" },
  { id: "1-2", slug: "laptop-office", name: "لپ‌تاپ اداری و دانشجویی", icon: "laptop", parentSlug: "laptop" },
  { id: "1-3", slug: "laptop-ultrabook", name: "لپ‌تاپ فوق‌سبک", icon: "laptop", parentSlug: "laptop" },
  { id: "1-4", slug: "laptop-apple", name: "مک‌بوک اپل", icon: "laptop", parentSlug: "laptop" },

  // کامپیوتر
  { id: "2-1", slug: "desktop-prebuilt", name: "کامپیوتر آماده", icon: "desktop", parentSlug: "desktop" },
  { id: "2-2", slug: "desktop-custom", name: "اسمبل اختصاصی گیمینگ", icon: "desktop", parentSlug: "desktop" },
  { id: "2-3", slug: "desktop-mini", name: "مینی پی‌سی", icon: "desktop", parentSlug: "desktop" },

  // کنسول بازی
  { id: "3-1", slug: "console-playstation", name: "PlayStation", icon: "gamepad", parentSlug: "console" },
  { id: "3-2", slug: "console-xbox", name: "Xbox", icon: "gamepad", parentSlug: "console" },
  { id: "3-3", slug: "console-nintendo", name: "Nintendo Switch", icon: "gamepad", parentSlug: "console" },
  { id: "3-4", slug: "console-games", name: "بازی و لوازم جانبی کنسول", icon: "gamepad", parentSlug: "console" },

  // مانیتور
  { id: "4-1", slug: "monitor-gaming", name: "مانیتور گیمینگ", icon: "monitor", parentSlug: "monitor" },
  { id: "4-2", slug: "monitor-office", name: "مانیتور اداری", icon: "monitor", parentSlug: "monitor" },
  { id: "4-3", slug: "monitor-design", name: "مانیتور طراحی و گرافیک", icon: "monitor", parentSlug: "monitor" },

  // قطعات سخت‌افزار
  { id: "5-1", slug: "parts-cpu", name: "پردازنده (CPU)", icon: "cpu", parentSlug: "parts" },
  { id: "5-2", slug: "parts-gpu", name: "کارت گرافیک (GPU)", icon: "cpu", parentSlug: "parts" },
  { id: "5-3", slug: "parts-ram", name: "رم (RAM)", icon: "cpu", parentSlug: "parts" },
  { id: "5-4", slug: "parts-motherboard", name: "مادربرد", icon: "cpu", parentSlug: "parts" },
  { id: "5-5", slug: "parts-psu-case", name: "پاور و کیس", icon: "cpu", parentSlug: "parts" },

  // ذخیره‌سازی
  { id: "6-1", slug: "storage-ssd", name: "هارد SSD اینترنال", icon: "drive", parentSlug: "storage" },
  { id: "6-2", slug: "storage-hdd-external", name: "هارد اکسترنال", icon: "drive", parentSlug: "storage" },
  { id: "6-3", slug: "storage-flash", name: "فلش مموری", icon: "drive", parentSlug: "storage" },
  { id: "6-4", slug: "storage-memory-card", name: "کارت حافظه", icon: "drive", parentSlug: "storage" },

  // لوازم جانبی گیمینگ
  { id: "7-1", slug: "accessories-headset", name: "هدست گیمینگ", icon: "headset", parentSlug: "accessories" },
  { id: "7-2", slug: "accessories-mouse-keyboard", name: "ماوس و کیبورد", icon: "mouse", parentSlug: "accessories" },
  { id: "7-3", slug: "accessories-chair", name: "صندلی گیمینگ", icon: "headset", parentSlug: "accessories" },
  { id: "7-4", slug: "accessories-controller", name: "دسته بازی", icon: "gamepad", parentSlug: "accessories" },

  // شبکه و اینترنت
  { id: "8-1", slug: "network-router", name: "روتر و مودم", icon: "wifi", parentSlug: "network" },
  { id: "8-2", slug: "network-switch", name: "سوییچ شبکه", icon: "wifi", parentSlug: "network" },
  { id: "8-3", slug: "network-wifi", name: "تجهیزات وای‌فای", icon: "wifi", parentSlug: "network" },
];

export const PRODUCTS: Product[] = [
  {
    id: "p1",
    slug: "lenovo-loq-15irx9",
    name: "لپ‌تاپ گیمینگ لنوو LOQ 15IRX9 نسل ۱۳ اینتل",
    brand: "LENOVO",
    categorySlug: "laptop-gaming",
    price: 89_500_000,
    regularPrice: 95_000_000,
    inStock: true,
    isBestSeller: true,
    rating: 4.6,
    reviewCount: 218,
    specChips: ["i7-13650HX", "RTX 4060", "۱۶GB"],
    images: ["/images/products/lenovo-loq-15irx9.svg"],
    icon: "laptop",
    sku: "LOQ-15IRX9-R7",
    shortDescription:
      "لپ‌تاپ گیمینگ با پردازنده نسل سیزدهم اینتل و کارت گرافیک RTX 4060، برای بازی‌های روز و کارهای گرافیکی سنگین.",
    descriptionHtml:
      "<p>لپ‌تاپ گیمینگ لنوو LOQ 15IRX9 با پردازنده نسل سیزدهم اینتل و کارت گرافیک RTX 4060 برای بازی‌های روز و کارهای گرافیکی سنگین طراحی شده است. سیستم خنک‌کاری دوگانه، فشار حرارتی بالا را در جلسات طولانی گیمینگ کنترل می‌کند و صفحه‌نمایش ۱۴۴ هرتز، تجربه‌ای روان و بدون افت فریم ارائه می‌دهد.</p><p>بدنه آلومینیومی و کیبورد بک‌لایت RGB، ظاهری حرفه‌ای به این لپ‌تاپ داده و باتری ۶۰ وات‌ساعتی آن برای استفاده روزمره خارج از پریز نیز کفایت می‌کند. این مدل به همراه گارانتی ۱۸ ماهه شرکتی، مستقیم از فروشگاه آیریک در بازار بزرگ کامپیوتر اصفهان عرضه می‌شود.</p>",
    specs: [
      { label: "پردازنده", value: "Intel Core i7-13650HX" },
      { label: "کارت گرافیک", value: "NVIDIA RTX 4060 8GB" },
      { label: "حافظه رم", value: "16GB DDR5" },
      { label: "حافظه ذخیره‌سازی", value: "1TB NVMe SSD" },
      { label: "صفحه‌نمایش", value: "15.6\" FHD IPS 144Hz" },
      { label: "باتری", value: "60Wh" },
      { label: "وزن", value: "2.3kg" },
      { label: "سیستم‌عامل", value: "Windows 11 Home" },
    ],
    variants: [
      { label: "حافظه و رم", options: ["i7 / 16GB / 512GB", "i7 / 16GB / 1TB", "i7 / 32GB / 1TB"] },
      { label: "رنگ بدنه", options: ["مشکی", "خاکستری"] },
    ],
  },
  {
    id: "p2",
    slug: "playstation-5-slim",
    name: "کنسول بازی PlayStation 5 Slim",
    brand: "SONY",
    categorySlug: "console-playstation",
    price: 54_900_000,
    inStock: true,
    isNew: true,
    rating: 4.8,
    reviewCount: 96,
    specChips: ["۱TB SSD", "۴K·۱۲۰fps"],
    images: ["/images/products/playstation-5-slim.svg"],
    icon: "gamepad",
    shortDescription: "کنسول نسل نهم سونی با حافظه ۱ ترابایتی و پشتیبانی از رزولوشن ۴K در ۱۲۰ فریم بر ثانیه.",
  },
  {
    id: "p3",
    slug: "asus-vivobook-15",
    name: "لپ‌تاپ ایسوس Vivobook 15",
    brand: "ASUS",
    categorySlug: "laptop-office",
    price: 42_300_000,
    inStock: true,
    rating: 4.3,
    reviewCount: 54,
    specChips: ["i5-1335U", "۸GB", "۵۱۲GB"],
    images: ["/images/products/asus-vivobook-15.svg"],
    icon: "laptop",
    shortDescription: "لپ‌تاپ سبک و همه‌کاره، مناسب کارهای اداری و دانشجویی.",
  },
  {
    id: "p4",
    slug: "hyperx-cloud-ii",
    name: "هدست گیمینگ HyperX Cloud II",
    brand: "HYPERX",
    categorySlug: "accessories-headset",
    price: 3_900_000,
    inStock: true,
    isBestSeller: true,
    rating: 4.7,
    reviewCount: 340,
    specChips: ["7.1 Surround"],
    images: ["/images/products/hyperx-cloud-ii.svg"],
    icon: "headset",
    shortDescription: "هدست گیمینگ با صدای فراگیر ۷.۱ و میکروفون حذف نویز.",
  },
  {
    id: "p5",
    slug: "asus-tuf-f15",
    name: "لپ‌تاپ ایسوس TUF Gaming F15",
    brand: "ASUS",
    categorySlug: "laptop-gaming",
    price: 64_200_000,
    inStock: true,
    rating: 4.4,
    reviewCount: 87,
    specChips: ["i7-12700H", "RTX 3050", "۱۶GB"],
    images: ["/images/products/asus-tuf-f15.svg"],
    icon: "laptop",
    shortDescription: "لپ‌تاپ گیمینگ مقاوم با بدنه استاندارد نظامی و خنک‌کاری قدرتمند.",
  },
  {
    id: "p6",
    slug: "lenovo-ideapad-slim-3",
    name: "لپ‌تاپ لنوو IdeaPad Slim 3",
    brand: "LENOVO",
    categorySlug: "laptop-office",
    price: 38_500_000,
    inStock: true,
    isNew: true,
    rating: 4.2,
    reviewCount: 41,
    specChips: ["Ryzen 5", "۸GB", "۵۱۲GB"],
    images: ["/images/products/lenovo-ideapad-slim-3.svg"],
    icon: "laptop",
    shortDescription: "لپ‌تاپ اقتصادی و سبک، انتخابی مناسب برای دانشجویان.",
  },
  {
    id: "p7",
    slug: "acer-nitro-v15",
    name: "لپ‌تاپ ایسر Nitro V15",
    brand: "ACER",
    categorySlug: "laptop-gaming",
    price: 71_800_000,
    inStock: true,
    rating: 4.5,
    reviewCount: 63,
    specChips: ["i7-13620H", "RTX 4050", "۱۶GB"],
    images: ["/images/products/acer-nitro-v15.svg"],
    icon: "laptop",
    shortDescription: "لپ‌تاپ گیمینگ میان‌رده با نسبت قیمت به عملکرد عالی.",
  },
  {
    id: "p8",
    slug: "macbook-air-m2",
    name: "مک‌بوک اپل Air M2",
    brand: "APPLE",
    categorySlug: "laptop-apple",
    price: 83_000_000,
    inStock: false,
    rating: 4.9,
    reviewCount: 122,
    specChips: ["M2", "۸GB", "۲۵۶GB"],
    images: ["/images/products/macbook-air-m2.svg"],
    icon: "laptop",
    shortDescription: "لپ‌تاپ فوق سبک اپل با تراشه M2 و باتری بلندمدت.",
  },
  {
    id: "p9",
    slug: "hp-victus-15",
    name: "لپ‌تاپ اچ‌پی Victus 15",
    brand: "HP",
    categorySlug: "laptop-gaming",
    price: 53_400_000,
    regularPrice: 58_000_000,
    inStock: true,
    rating: 4.1,
    reviewCount: 29,
    specChips: ["i5-13420H", "RTX 3050", "۱۶GB"],
    images: ["/images/products/hp-victus-15.svg"],
    icon: "laptop",
    shortDescription: "لپ‌تاپ گیمینگ ورودی با طراحی ساده و عملکرد قابل اتکا.",
  },
  {
    id: "p10",
    slug: "logitech-g502",
    name: "ماوس گیمینگ لاجیتک G502",
    brand: "LOGITECH",
    categorySlug: "accessories-mouse-keyboard",
    price: 4_100_000,
    inStock: true,
    rating: 4.6,
    reviewCount: 210,
    specChips: ["۲۵۶۰۰ DPI"],
    images: ["/images/products/logitech-g502.svg"],
    icon: "mouse",
    shortDescription: "ماوس گیمینگ با سنسور دقیق و ۱۱ دکمه قابل برنامه‌ریزی.",
  },
];

export const POSTS: Post[] = [
  {
    id: "b1",
    slug: "gaming-laptop-buying-guide-2026",
    title: "راهنمای خرید لپ‌تاپ گیمینگ در سال ۲۰۲۶؛ روی چه مشخصاتی تمرکز کنیم؟",
    excerpt:
      "پیش از خرید لپ‌تاپ گیمینگ باید نسبت کارت گرافیک به پردازنده، کیفیت سیستم خنک‌کاری و نرخ‌تازه‌سازی صفحه‌نمایش را کنار هم بسنجید.",
    categoryLabel: "راهنمای خرید",
    categorySlug: "buying-guide",
    image: "/images/posts/gaming-laptop-buying-guide-2026.svg",
    dateIso: "2026-07-06",
    readMinutes: 6,
    icon: "laptop",
    contentHtml:
      "<p>پیش از خرید لپ‌تاپ گیمینگ باید نسبت کارت گرافیک به پردازنده، کیفیت سیستم خنک‌کاری و نرخ‌تازه‌سازی صفحه‌نمایش را کنار هم بسنجید. در این راهنما قدم‌به‌قدم نشان می‌دهیم کدام مشخصه‌ها واقعاً روی تجربه بازی تأثیر می‌گذارند و کجا می‌شود در هزینه صرفه‌جویی کرد.</p><h2>کارت گرافیک مهم‌تر از پردازنده است</h2><p>برای اکثر بازی‌های روز، کارت گرافیک (GPU) نقش تعیین‌کننده‌تری نسبت به پردازنده دارد. سرمایه‌گذاری روی یک RTX 4060 معمولاً نتیجه بهتری از یک i9 با گرافیک ضعیف‌تر می‌دهد.</p><h2>خنک‌کاری را دست کم نگیرید</h2><p>لپ‌تاپ‌های گیمینگ زیر بار سنگین به سرعت داغ می‌شوند. سیستم خنک‌کاری دوگانه یا سه‌گانه، عملکرد پایدار در جلسات طولانی را تضمین می‌کند.</p>",
  },
  {
    id: "b2",
    slug: "ps5-vs-xbox-series-x",
    title: "PS5 یا Xbox Series X؛ کدام کنسول برای شما مناسب‌تر است؟",
    excerpt: "مقایسه‌ای واقعی بر اساس کتابخانه بازی‌ها، قیمت و تجربه کاربری دو کنسول محبوب بازار.",
    categoryLabel: "مقایسه",
    categorySlug: "comparison",
    image: "/images/posts/ps5-vs-xbox-series-x.svg",
    dateIso: "2026-06-30",
    readMinutes: 4,
    icon: "gamepad",
    contentHtml:
      "<p>مقایسه‌ای واقعی بر اساس کتابخانه بازی‌ها، قیمت و تجربه کاربری دو کنسول محبوب بازار.</p><p>هر دو کنسول از نظر سخت‌افزاری بسیار نزدیک هستند؛ تفاوت اصلی در انحصاری‌های هر پلتفرم و اکوسیستم اشتراکی آن‌هاست.</p>",
  },
  {
    id: "b3",
    slug: "internal-vs-external-ssd",
    title: "SSD اینترنال بخریم یا اکسترنال؟ راهنمای انتخاب حافظه ذخیره‌سازی",
    excerpt: "تفاوت سرعت، قیمت و کاربرد SSDهای اینترنال و اکسترنال را با مثال‌های واقعی بررسی می‌کنیم.",
    categoryLabel: "آموزش",
    categorySlug: "tutorial",
    image: "/images/posts/internal-vs-external-ssd.svg",
    dateIso: "2026-06-23",
    readMinutes: 5,
    icon: "drive",
    contentHtml:
      "<p>تفاوت سرعت، قیمت و کاربرد SSDهای اینترنال و اکسترنال را با مثال‌های واقعی بررسی می‌کنیم.</p><p>اگر سرعت بالا و نصب سیستم‌عامل مد نظرتان است، SSD اینترنال NVMe انتخاب درستی است؛ برای بکاپ‌گیری و جابه‌جایی فایل، مدل اکسترنال کاربردی‌تر است.</p>",
  },
  {
    id: "b4",
    slug: "cpu-cooler-air-vs-liquid",
    title: "کول‌تر خنک‌کننده پردازنده؛ هوایی بخریم یا مایع؟",
    excerpt:
      "برای سیستم‌های گیمینگ و رندر سنگین، انتخاب درست خنک‌کننده تفاوت زیادی در دمای پردازنده ایجاد می‌کند.",
    categoryLabel: "راهنمای خرید",
    categorySlug: "buying-guide",
    image: "/images/posts/cpu-cooler-air-vs-liquid.svg",
    dateIso: "2026-06-18",
    readMinutes: 7,
    icon: "cpu",
    contentHtml:
      "<p>برای سیستم‌های گیمینگ و رندر سنگین، انتخاب درست خنک‌کننده تفاوت زیادی در دمای پردازنده ایجاد می‌کند.</p>",
  },
  {
    id: "b5",
    slug: "intel-core-ultra-arrives-in-iran",
    title: "نسل جدید پردازنده‌های اینتل Core Ultra به بازار ایران رسید",
    excerpt: "بررسی مشخصات و قیمت اولین لپ‌تاپ‌های مجهز به پردازنده‌های نسل جدید اینتل در فروشگاه آیریک.",
    categoryLabel: "اخبار",
    categorySlug: "news",
    image: "/images/posts/intel-core-ultra-arrives-in-iran.svg",
    dateIso: "2026-06-10",
    readMinutes: 3,
    icon: "chip-brand",
    contentHtml:
      "<p>بررسی مشخصات و قیمت اولین لپ‌تاپ‌های مجهز به پردازنده‌های نسل جدید اینتل در فروشگاه آیریک.</p>",
  },
  {
    id: "b6",
    slug: "gaming-monitor-buying-guide",
    title: "مانیتور گیمینگ مناسب چه ویژگی‌هایی باید داشته باشد؟",
    excerpt: "نرخ‌تازه‌سازی، زمان پاسخ و نوع پنل را قبل از خرید مانیتور گیمینگ جدی بگیرید.",
    categoryLabel: "راهنمای خرید",
    categorySlug: "buying-guide",
    image: "/images/posts/gaming-monitor-buying-guide.svg",
    dateIso: "2026-06-02",
    readMinutes: 6,
    icon: "monitor",
    contentHtml: "<p>نرخ‌تازه‌سازی، زمان پاسخ و نوع پنل را قبل از خرید مانیتور گیمینگ جدی بگیرید.</p>",
  },
];
